version: "3.8"

services:
  nginx:
    build: ./images/nginx/
    volumes:
      - nginx_conf:/etc/nginx/
      - ./frontend:/www
      - ./docker_data/nginx_conf:/etc/nginx/conf.d
      - ./docker_data/php_conf/ini:/usr/local/etc/php/conf.d
    # Port ajouté
    ports:
      - "80:80"
      # Port 81 mappé
      - "81:81"
    networks:
      custom_net:
        ipv4_address: 10.5.0.2

  php:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    hostname: cinetech.dok
    volumes:
      - ./frontend:/www
    networks:
      custom_net:
        ipv4_address: 10.5.0.3

  node:
    hostname: api.cinetech.dok
    build: ./images/node/
    env_file: ./backend/.env
    volumes:
      - ./backend:/www
    networks:
      custom_net:
        ipv4_address: 10.5.0.4
volumes:
  nginx_conf:

networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
